def build_compatibility_handlers(
    main_menu,
    do_login,
    do_search,
    manage_profiles,
    browse_my_list,
    browse_my_list_group,
    toggle_mylist,
    select_profile,
    apply_profile,
    browse_series,
    do_logout,
    confirm_logout,
    refresh_account_info,
    search_group,
    show_series_detail,
    show_series_season,
    browse_placement_row,
    browse_tv_shows,
    browse_tv_genre,
    browse_series_categories,
    browse_series_genre,
    browse_movie_categories,
    browse_movie_genre,
    browse_category,
    play_item,
    select_iptv_channels,
):
    return {
        'main_menu': main_menu,
        'do_login': do_login,
        'do_search': do_search,
        'manage_profiles': manage_profiles,
        'browse_my_list': browse_my_list,
        'browse_my_list_group': browse_my_list_group,
        'toggle_mylist': toggle_mylist,
        'select_profile': select_profile,
        'apply_profile': apply_profile,
        'browse_series': browse_series,
        'do_logout': do_logout,
        'confirm_logout': confirm_logout,
        'refresh_account_info': refresh_account_info,
        'search_group': search_group,
        'show_series_detail': show_series_detail,
        'show_series_season': show_series_season,
        'browse_placement_row': browse_placement_row,
        'browse_tv_shows': browse_tv_shows,
        'browse_tv_genre': browse_tv_genre,
        'browse_series_categories': browse_series_categories,
        'browse_series_genre': browse_series_genre,
        'browse_movie_categories': browse_movie_categories,
        'browse_movie_genre': browse_movie_genre,
        'browse_category': browse_category,
        'play_item': play_item,
        'select_iptv_channels': select_iptv_channels,
    }
